### ISSUE TITLE
Login page is now broken

### ISSUE THREAD

**Issue by asfopoo** [asfopoo/CS320_OrganTrail#12]
Now that the database work for the register page the login page needs to be updated to pull from database... or session, however that works

**Comment by asfopoo** [comment]
Database stuff is updated but currently lets any username and password in.  In the if/else block, if you switch the !resultSet.has to resultSet.has, then switch the return statements, it wont let anyone in

**Comment by asfopoo** [comment]
login page has database stuff but needs to compare to the unputed username and password to the database username and password to verify account

**Comment by Jumbofile** [comment]
Fixed using user.equals() instead of ==
